# Generated by Django 4.0.8 on 2024-04-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_semester_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(blank=True, choices=[('Nhava_Sheva_Port', 'Nhava_Sheva_Port'), ('Port of Singapore', 'Port of Singapore'), ('Port of Rotterdam', 'Port of Rotterdam'), ('Port of Hong Kong', 'Port of Hong Kong'), ('Port of Busan', 'Port of Busan'), ('Port of Antwerp', 'Port of Antwerp'), ('Port of Hamburg', 'Port of Hamburg'), ('Port of Los Angeles', 'Port of Los Angeles'), ('Port of Long Beach', 'Port of Long Beach'), ('Port of Dubai', 'Port of Dubai'), ('Port_Los_Angeles', 'Port_Los_Angeles')], max_length=100),
        ),
    ]
