# Generated by Django 4.0.8 on 2024-04-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_upload_file_alter_uploadvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pincode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='receiver_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='receiver_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='sender_contact',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='sender_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Cargo Ship', 'Cargo Ship'), ('Airplane', 'Airplane'), ('Goods Carrier', 'Goods Carrier')], max_length=25, null=True),
        ),
    ]
