# Generated by Django 4.0.8 on 2024-04-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_order_weight_course_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='Default Code', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='First', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.TextField(default='Default Summary', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='Default Title', max_length=200),
        ),
    ]
