# Generated by Django 4.0.8 on 2024-04-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='order_weight',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='course',
            name='receiver_address',
        ),
        migrations.RemoveField(
            model_name='course',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sender_contact',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sender_name',
        ),
    ]
