# Generated by Django 4.0.8 on 2024-04-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='volume',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
