# Generated by Django 4.0.8 on 2024-04-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_course_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order_type',
            field=models.CharField(choices=[('PERISHABLE', 'PERISHABLE'), ('DELICAT', 'DELICAT'), ('NORMAL', 'NORMAL'), ('OIL', 'OIL')], max_length=200, null=True),
        ),
    ]
