# Generated by Django 4.0.8 on 2024-04-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Cargo Ship', 'Cargo Ship'), ('Airplane', 'Airplane'), ('Goods Carrier', 'Goods Carrier')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], max_length=20, null=True),
        ),
    ]
