# Generated by Django 4.0.8 on 2024-04-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_capacity_alter_student_level_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vessel_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
