# Generated by Django 4.0.8 on 2024-04-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_user_vessel_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vessel_type',
            field=models.CharField(blank=True, choices=[('PERISHABLE', 'PERISHABLE'), ('DELICAT', 'DELICAT'), ('NORMAL', 'NORMAL'), ('OIL', 'OIL')], max_length=20, null=True),
        ),
    ]
